# Generated by Django 4.2.10 on 2024-02-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('correction_point', models.IntegerField()),
                ('pool_month', models.CharField(max_length=255)),
                ('pool_year', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
